language: 'ru_ru'
# Язык плагина.
msgcooldown: 10
# Задержка между сообщениями
delay: 100
# Время между тем, как лечь спать с последним нужным игроком, и пропуском ночи.
playermustsleep: 'Четверть'
# Количество необходимых игроков.Может быть: 'custom', 'Половина', 'Четверть', 'Все'.
playersneed: 2
# Пользовательское количество игроков, необходимое для пропуска ночи.


